<#
.SYNOPSIS
    Silently uninstall Biobot Uro software without Python.

.DESCRIPTION
    Step 1 - Uninstall UroBiopsy if installed
    Step 2 - Uninstall UroConnect if installed
    Step 3 - Uninstall UroFusion if installed
    Step 4 - Uninstall UroReview if installed
    Step 5 - Uninstall UroTherapy if installed
    Step 6 - Display status and update log file

.NOTES
    Run as Administrator.
    Default log file: C:\ProgramData\BiobotUroSoftware\Uninstall-Biobot-UroSoftware.log

.EXAMPLES
    powershell.exe -ExecutionPolicy Bypass -NoProfile -File .\Uninstall-Biobot-UroSoftware.ps1
    powershell.exe -ExecutionPolicy Bypass -NoProfile -File .\Uninstall-Biobot-UroSoftware.ps1 -ShowUI
    powershell.exe -ExecutionPolicy Bypass -NoProfile -File .\Uninstall-Biobot-UroSoftware.ps1 -DryRun
#>

param(
    [switch]$ShowUI,
    [switch]$DryRun,
    [int]$TimeoutSeconds = 1800
)

# =========================
# Config
# =========================

$LogDir  = "C:\ProgramData\BiobotUroSoftware"
$LogFile = Join-Path $LogDir "Uninstall-Biobot-UroSoftware.log"

# Most Uninstaller.exe files generated by NSIS use /S for silent uninstall.
# If Biobot's uninstaller uses another silent switch, change SilentArgs below.
$DefaultSilentArgs = "/S"

$Products = @(
    @{
        Name = "UroBiopsy"
        MatchRegex = "(?i)(UroBiopsy|Biobot.*UroBiopsy)"
        KnownUninstallers = @(
            "C:\Program Files\Biobot\UroBiopsy\Uninstaller.exe"
        )
        SilentArgs = $DefaultSilentArgs
        UseNsisWaitPath = $true
    },
    @{
        Name = "UroConnect"
        MatchRegex = "(?i)(UroConnect|Biobot.*UroConnect)"
        KnownUninstallers = @(
            "C:\Program Files\Biobot\UroConnect\Uninstaller.exe"
        )
        SilentArgs = $DefaultSilentArgs
        UseNsisWaitPath = $true
    },
    @{
        Name = "UroFusion"
        MatchRegex = "(?i)(UroFusion|Biobot.*UroFusion)"
        KnownUninstallers = @(
            "C:\Program Files\Biobot\UroFusion\Uninstaller.exe"
        )
        SilentArgs = $DefaultSilentArgs
        UseNsisWaitPath = $true
    },
    @{
        Name = "UroReview"
        MatchRegex = "(?i)(UroReview|Biobot.*UroReview)"
        KnownUninstallers = @(
            "C:\Program Files\Biobot\UroReview\Uninstaller.exe"
        )
        SilentArgs = $DefaultSilentArgs
        UseNsisWaitPath = $true
    },
    @{
        Name = "UroTherapy"
        MatchRegex = "(?i)(UroTherapy|Biobot.*UroTherapy)"
        KnownUninstallers = @(
            "C:\Program Files\Biobot\UroTherapy\Uninstaller.exe"
        )
        SilentArgs = $DefaultSilentArgs
        UseNsisWaitPath = $true
    }
)

# =========================
# Log helpers
# =========================

function Initialize-Log {
    if (-not (Test-Path $LogDir)) {
        New-Item -Path $LogDir -ItemType Directory -Force | Out-Null
    }

    Add-Content -Path $LogFile -Value ""
    Add-Content -Path $LogFile -Value "============================================================"
    Add-Content -Path $LogFile -Value "Biobot Uro software uninstall started: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    Add-Content -Path $LogFile -Value "Computer: $env:COMPUTERNAME"
    Add-Content -Path $LogFile -Value "User: $env:USERDOMAIN\$env:USERNAME"
    Add-Content -Path $LogFile -Value "DryRun: $DryRun"
    Add-Content -Path $LogFile -Value "TimeoutSeconds: $TimeoutSeconds"
    Add-Content -Path $LogFile -Value "============================================================"
}

function Write-Log {
    param(
        [string]$Message,
        [string]$Level = "INFO"
    )

    $line = "[{0}] [{1}] {2}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Level, $Message
    Write-Host $line
    Add-Content -Path $LogFile -Value $line
}

function Test-IsAdmin {
    try {
        $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
        $principal = New-Object Security.Principal.WindowsPrincipal($identity)
        return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    }
    catch {
        return $false
    }
}

# =========================
# Registry detection
# =========================

function Get-UninstallRegistryEntries {
    $uninstallPaths = @(
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*",
        "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*",
        "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*"
    )

    foreach ($path in $uninstallPaths) {
        Get-ItemProperty -Path $path -ErrorAction SilentlyContinue |
            Where-Object { $_.DisplayName } |
            ForEach-Object {
                [pscustomobject]@{
                    DisplayName = $_.DisplayName
                    DisplayVersion = $_.DisplayVersion
                    Publisher = $_.Publisher
                    InstallLocation = $_.InstallLocation
                    UninstallString = $_.UninstallString
                    QuietUninstallString = $_.QuietUninstallString
                    PSChildName = $_.PSChildName
                    PSPath = $_.PSPath
                }
            }
    }
}

function Get-InstalledEntriesForProduct {
    param(
        [hashtable]$Product
    )

    $results = @()
    $seen = @{}

    foreach ($entry in Get-UninstallRegistryEntries) {
        $combined = @(
            $entry.DisplayName,
            $entry.Publisher,
            $entry.InstallLocation,
            $entry.UninstallString,
            $entry.QuietUninstallString
        ) -join "`n"

        if ($combined -match $Product.MatchRegex) {
            $key = [string]$entry.PSPath
            if (-not $seen.ContainsKey($key)) {
                $seen[$key] = $true
                $results += $entry
            }
        }
    }

    return $results
}

function Test-ProductStillInstalled {
    param(
        [hashtable]$Product
    )

    $entries = Get-InstalledEntriesForProduct -Product $Product
    if ($entries.Count -gt 0) {
        return $true
    }

    foreach ($path in $Product.KnownUninstallers) {
        if ($path -and (Test-Path $path)) {
            return $true
        }
    }

    return $false
}

# =========================
# Command parsing and building
# =========================

function Split-CommandLine {
    param(
        [string]$CommandLine
    )

    $cmd = $CommandLine.Trim()

    if ($cmd -match '^\s*"([^"]+)"\s*(.*)$') {
        return [pscustomobject]@{
            FilePath = $matches[1]
            Arguments = $matches[2].Trim()
        }
    }

    if ($cmd -match '^\s*(MsiExec(?:\.exe)?)\s+(.*)$') {
        return [pscustomobject]@{
            FilePath = "msiexec.exe"
            Arguments = $matches[2].Trim()
        }
    }

    $lower = $cmd.ToLowerInvariant()
    $exeIndex = $lower.IndexOf(".exe")

    if ($exeIndex -ge 0) {
        $filePath = $cmd.Substring(0, $exeIndex + 4).Trim()
        $arguments = ""
        if ($cmd.Length -gt ($exeIndex + 4)) {
            $arguments = $cmd.Substring($exeIndex + 4).Trim()
        }

        return [pscustomobject]@{
            FilePath = $filePath
            Arguments = $arguments
        }
    }

    return [pscustomobject]@{
        FilePath = "cmd.exe"
        Arguments = "/c `"$cmd`""
    }
}

function Get-MsiProductCode {
    param(
        $Entry
    )

    if ($Entry.PSChildName -and ($Entry.PSChildName -match '^\{[0-9A-Fa-f\-]{36}\}$')) {
        return $Entry.PSChildName
    }

    if ($Entry.UninstallString -and ($Entry.UninstallString -match '\{[0-9A-Fa-f\-]{36}\}')) {
        return $matches[0]
    }

    if ($Entry.QuietUninstallString -and ($Entry.QuietUninstallString -match '\{[0-9A-Fa-f\-]{36}\}')) {
        return $matches[0]
    }

    return $null
}

function Test-HasSilentSwitch {
    param(
        [string]$Arguments
    )

    if (-not $Arguments) {
        return $false
    }

    return ($Arguments -match '(?i)(^|\s)(/S|/silent|/quiet|/qn|/verysilent|-s|--silent|--quiet)(\s|$)')
}

function Test-HasNsisWaitPath {
    param(
        [string]$Arguments
    )

    if (-not $Arguments) {
        return $false
    }

    return ($Arguments -match '(?i)(^|\s)_\?=')
}

function Add-SilentArguments {
    param(
        [hashtable]$Product,
        [string]$FilePath,
        [string]$Arguments
    )

    $result = ""
    if ($Arguments) {
        $result = $Arguments.Trim()
    }

    if (-not (Test-HasSilentSwitch -Arguments $result)) {
        if ($Product.SilentArgs) {
            $result = ("$result $($Product.SilentArgs)").Trim()
        }
    }

    # NSIS uninstallers can start a child process and return early.
    # Adding _?=<install folder> as the last argument helps the script wait for the real uninstall operation.
    # NSIS requires no quotes around the _?= path, even if it contains spaces.
    if ($Product.UseNsisWaitPath -and -not (Test-HasNsisWaitPath -Arguments $result)) {
        try {
            $directory = Split-Path -Path $FilePath -Parent
            if ($directory) {
                $result = ("$result _?=$directory").Trim()
            }
        }
        catch {
            # Keep the current arguments if the path cannot be parsed.
        }
    }

    return $result
}

function New-RegistryUninstallTarget {
    param(
        [hashtable]$Product,
        $Entry
    )

    # Prefer QuietUninstallString if available because it is vendor-provided for unattended removal.
    if ($Entry.QuietUninstallString) {
        $parsed = Split-CommandLine -CommandLine $Entry.QuietUninstallString
        return [pscustomobject]@{
            Source = "Registry QuietUninstallString"
            Description = "$($Entry.DisplayName)"
            FilePath = $parsed.FilePath
            Arguments = $parsed.Arguments
        }
    }

    # MSI uninstall handling.
    $msiCode = Get-MsiProductCode -Entry $Entry
    if ($msiCode) {
        return [pscustomobject]@{
            Source = "MSI ProductCode"
            Description = "$($Entry.DisplayName)"
            FilePath = "msiexec.exe"
            Arguments = "/x $msiCode /qn /norestart"
        }
    }

    # Fall back to UninstallString and add silent args if not already present.
    if ($Entry.UninstallString) {
        $parsed = Split-CommandLine -CommandLine $Entry.UninstallString
        $args = Add-SilentArguments -Product $Product -FilePath $parsed.FilePath -Arguments $parsed.Arguments

        return [pscustomobject]@{
            Source = "Registry UninstallString"
            Description = "$($Entry.DisplayName)"
            FilePath = $parsed.FilePath
            Arguments = $args
        }
    }

    return $null
}

function New-KnownPathUninstallTarget {
    param(
        [hashtable]$Product,
        [string]$UninstallerPath
    )

    if (-not $UninstallerPath) {
        return $null
    }

    if (-not (Test-Path $UninstallerPath)) {
        return $null
    }

    $args = Add-SilentArguments -Product $Product -FilePath $UninstallerPath -Arguments ""

    return [pscustomobject]@{
        Source = "Known Uninstaller Path"
        Description = $UninstallerPath
        FilePath = $UninstallerPath
        Arguments = $args
    }
}

function Get-UninstallTargetsForProduct {
    param(
        [hashtable]$Product
    )

    $targets = @()
    $seen = @{}

    foreach ($entry in Get-InstalledEntriesForProduct -Product $Product) {
        $target = New-RegistryUninstallTarget -Product $Product -Entry $entry
        if ($target) {
            $key = ("$($target.FilePath)|$($target.Arguments)").ToLowerInvariant()
            if (-not $seen.ContainsKey($key)) {
                $seen[$key] = $true
                $targets += $target
            }
        }
    }

    foreach ($path in $Product.KnownUninstallers) {
        $target = New-KnownPathUninstallTarget -Product $Product -UninstallerPath $path
        if ($target) {
            $key = ("$($target.FilePath)|$($target.Arguments)").ToLowerInvariant()
            if (-not $seen.ContainsKey($key)) {
                $seen[$key] = $true
                $targets += $target
            }
        }
    }

    return $targets
}

# =========================
# Process execution
# =========================

function Invoke-UninstallProcess {
    param(
        [string]$FilePath,
        [string]$Arguments,
        [int]$TimeoutSeconds
    )

    if ($DryRun) {
        Write-Log "[DRY-RUN] Would run: `"$FilePath`" $Arguments"
        return [pscustomobject]@{
            ExitCode = 0
            TimedOut = $false
            Detail = "Dry run only"
        }
    }

    try {
        Write-Log "Running: `"$FilePath`" $Arguments"

        $process = Start-Process `
            -FilePath $FilePath `
            -ArgumentList $Arguments `
            -WindowStyle Hidden `
            -PassThru `
            -ErrorAction Stop

        $timeoutMs = [Math]::Min($TimeoutSeconds * 1000, [int]::MaxValue)
        $completed = $process.WaitForExit($timeoutMs)

        if (-not $completed) {
            Write-Log "Timeout reached. Killing process id $($process.Id)." "ERROR"
            try {
                $process.Kill()
            }
            catch {
                Write-Log "Failed to kill timed-out process: $($_.Exception.Message)" "ERROR"
            }

            return [pscustomobject]@{
                ExitCode = 124
                TimedOut = $true
                Detail = "Timeout"
            }
        }

        return [pscustomobject]@{
            ExitCode = $process.ExitCode
            TimedOut = $false
            Detail = "Completed"
        }
    }
    catch {
        Write-Log "Failed to start uninstall process: $($_.Exception.Message)" "ERROR"
        return [pscustomobject]@{
            ExitCode = 9999
            TimedOut = $false
            Detail = $_.Exception.Message
        }
    }
}

function Invoke-ProductUninstall {
    param(
        [hashtable]$Product
    )

    Write-Log "------------------------------------------------------------"
    Write-Log "Processing $($Product.Name)"

    $targets = Get-UninstallTargetsForProduct -Product $Product

    if ($targets.Count -eq 0) {
        Write-Log "$($Product.Name) was not detected. Skipping."
        return [pscustomobject]@{
            Product = $Product.Name
            Status = "Skipped"
            ExitCodes = ""
            Detail = "Not installed or uninstall command not found"
        }
    }

    $exitCodes = @()
    $hasFailure = $false
    $rebootRequired = $false

    foreach ($target in $targets) {
        Write-Log "Uninstall source: $($target.Source)"
        Write-Log "Target: $($target.Description)"

        $runResult = Invoke-UninstallProcess `
            -FilePath $target.FilePath `
            -Arguments $target.Arguments `
            -TimeoutSeconds $TimeoutSeconds

        $exitCodes += $runResult.ExitCode
        Write-Log "$($Product.Name) uninstall returned exit code: $($runResult.ExitCode)"

        switch ($runResult.ExitCode) {
            0    { }
            3010 { $rebootRequired = $true }
            1641 { $rebootRequired = $true }
            default { $hasFailure = $true }
        }
    }

    Start-Sleep -Seconds 3

    if ($DryRun) {
        return [pscustomobject]@{
            Product = $Product.Name
            Status = "DryRun"
            ExitCodes = ($exitCodes -join ",")
            Detail = "No uninstall executed"
        }
    }

    $stillInstalled = Test-ProductStillInstalled -Product $Product

    if ($hasFailure) {
        Write-Log "$($Product.Name) uninstall failed or returned a non-success exit code." "ERROR"
        return [pscustomobject]@{
            Product = $Product.Name
            Status = "Failed"
            ExitCodes = ($exitCodes -join ",")
            Detail = "Uninstall failed or non-success exit code"
        }
    }

    if ($stillInstalled) {
        Write-Log "$($Product.Name) uninstall completed, but the product is still detected. Please verify manually." "WARN"
        return [pscustomobject]@{
            Product = $Product.Name
            Status = "Warning"
            ExitCodes = ($exitCodes -join ",")
            Detail = "Completed, but product still detected"
        }
    }

    if ($rebootRequired) {
        Write-Log "$($Product.Name) uninstalled. Reboot required." "WARN"
        return [pscustomobject]@{
            Product = $Product.Name
            Status = "SuccessRebootRequired"
            ExitCodes = ($exitCodes -join ",")
            Detail = "Uninstalled, reboot required"
        }
    }

    Write-Log "$($Product.Name) uninstalled successfully."
    return [pscustomobject]@{
        Product = $Product.Name
        Status = "Success"
        ExitCodes = ($exitCodes -join ",")
        Detail = "Uninstalled"
    }
}

# =========================
# Main
# =========================

Initialize-Log

if (-not (Test-IsAdmin)) {
    Write-Log "This script is not running as Administrator. Uninstall may fail. Use Run-Uninstall-Biobot-UroSoftware.cmd to auto-elevate." "WARN"
}

Write-Log "Starting Biobot Uro software uninstall sequence."
Write-Log "Log file: $LogFile"

$results = @()

foreach ($product in $Products) {
    $results += Invoke-ProductUninstall -Product $product
}

Write-Log "------------------------------------------------------------"
Write-Log "Uninstall summary:"

foreach ($result in $results) {
    Write-Log "$($result.Product): $($result.Status) | ExitCode(s): $($result.ExitCodes) | $($result.Detail)"
}

$failed = @($results | Where-Object { $_.Status -eq "Failed" })
$warnings = @($results | Where-Object { $_.Status -eq "Warning" })
$rebootRequired = @($results | Where-Object { $_.Status -eq "SuccessRebootRequired" })

if ($failed.Count -gt 0) {
    $finalStatus = "Completed with failures"
    $finalExitCode = 1
}
elseif ($warnings.Count -gt 0) {
    $finalStatus = "Completed with warnings"
    $finalExitCode = 0
}
elseif ($rebootRequired.Count -gt 0) {
    $finalStatus = "Completed successfully. Reboot required."
    $finalExitCode = 3010
}
else {
    $finalStatus = "Completed successfully"
    $finalExitCode = 0
}

Write-Log "Final status: $finalStatus"
Write-Log "Biobot Uro software uninstall finished: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Log "============================================================"

Write-Host ""
Write-Host "============================================================"
Write-Host "Biobot Uro software uninstall summary"
Write-Host "============================================================"
$results | Format-Table Product, Status, ExitCodes, Detail -AutoSize
Write-Host "Log file: $LogFile"
Write-Host "Final status: $finalStatus"
Write-Host "============================================================"

if ($ShowUI) {
    try {
        $message = "Biobot Uro software uninstall finished.`n`nStatus: $finalStatus`nLog: $LogFile"
        $shell = New-Object -ComObject WScript.Shell
        $shell.Popup($message, 0, "Biobot Uro Software Uninstall Status", 64) | Out-Null
    }
    catch {
        Write-Log "Unable to display UI popup: $($_.Exception.Message)" "WARN"
    }
}

exit $finalExitCode
